#!/usr/bin/env node
/**
 * Flatten everything scraped from provider websites into one table.
 *
 *   node scripts/export-table.mjs
 *
 * One row per provider (all 111, so providers with no website stay visible as
 * gaps). Joins the stage outputs in data/enrichment/:
 *   providers.json  (20 resolve)   website + how it was verified
 *   crawl.json      (30 crawl)     pages fetched and how much text
 *   facts.json      (40 extract)   Gemini/keyword facts + verbatim quotes
 *   photos.json     (50 images)    screened photos
 *
 * Writes data/scraped-table.csv (open in Excel / Google Sheets) and
 * data/scraped-table.md (renders on GitHub).
 */
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const work = (f) => path.join(ROOT, "data", "enrichment", f);

async function load(file, fallback = []) {
  try {
    return JSON.parse(await readFile(work(file), "utf8"));
  } catch {
    return fallback;
  }
}

const byProvider = (rows) => new Map(rows.map((r) => [r.provider, r]));
const list = (xs) => (xs ?? []).filter(Boolean);
const yesNo = (v) => (v === true ? "yes" : v === false ? "no" : "");

const COLUMNS = [
  ["Provider", (r) => r.p.provider],
  ["NYC K-5 sites", (r) => r.p.siteCount],
  ["Boroughs", (r) => list(r.p.boroughs)],
  ["Website", (r) => r.p.website ?? ""],
  ["Website verified by", (r) => (r.p.website ? r.p.resolvedVia ?? "" : "")],
  ["Website match", (r) => (r.p.website ? r.p.confidence ?? "" : "not found")],
  ["Pages crawled", (r) => r.c?.pages?.length ?? 0],
  ["Crawled page URLs", (r) => list(r.c?.pages?.map((pg) => pg.url))],
  ["Text scraped (chars)", (r) => r.c?.pages?.reduce((s, pg) => s + (pg.text?.length ?? 0), 0) ?? 0],
  ["Crawl error", (r) => r.c?.error ?? ""],
  ["Extraction method", (r) => r.f?.method ?? ""],
  ["Extraction confidence", (r) => r.f?.confidence ?? ""],
  ["Offers K-5 programming", (r) => yesNo(r.f?.hasK5Programming)],
  ["Summary", (r) => r.f?.summary ?? ""],
  ["Subjects", (r) => list(r.f?.subjects)],
  ["Subject quotes", (r) => list(r.f?.subjectEvidence?.map((e) => `${e.subject}: "${e.quote}"`))],
  ["STEM tools", (r) => list(r.f?.stemTools)],
  ["STEM tool quotes", (r) => list(r.f?.evidence)],
  ["Activities", (r) => list(r.f?.activities)],
  ["Cost", (r) => r.f?.costTier ?? ""],
  ["Hours", (r) => r.f?.hoursText ?? ""],
  ["Email", (r) => r.f?.contactEmail ?? ""],
  ["Phone", (r) => r.f?.contactPhone ?? ""],
  ["Photos kept", (r) => r.ph?.photos?.length ?? 0],
  ["Photos reviewed by Gemini", (r) => r.ph?.photos?.filter((x) => x.judged).length ?? 0],
  ["Carousel-ready photos", (r) => r.ph?.photos?.filter((x) => x.carouselReady).length ?? 0],
  ["Tools visible in photos", (r) => [...new Set(r.ph?.photos?.flatMap((x) => x.visibleTools ?? []) ?? [])]],
  ["Photo captions", (r) => list(r.ph?.photos?.map((x) => x.caption))],
  ["Photo URLs", (r) => list(r.ph?.photos?.map((x) => x.url))],
];

const cell = (v) => (Array.isArray(v) ? v : [v ?? ""]);

function toCsv(rows) {
  const esc = (s) => {
    const t = String(s);
    return /[",\n\r]/.test(t) ? `"${t.replace(/"/g, '""')}"` : t;
  };
  const lines = [COLUMNS.map(([h]) => esc(h)).join(",")];
  for (const r of rows) lines.push(COLUMNS.map(([, get]) => esc(cell(get(r)).join("\n"))).join(","));
  return lines.join("\r\n") + "\r\n";
}

function toMarkdown(rows) {
  const esc = (s) => String(s).replace(/\|/g, "\\|").replace(/\s*\n\s*/g, " ");
  const head = `| ${COLUMNS.map(([h]) => h).join(" | ")} |`;
  const rule = `|${COLUMNS.map(() => "---").join("|")}|`;
  const body = rows.map(
    (r) => `| ${COLUMNS.map(([, get]) => cell(get(r)).map(esc).join("<br>")).join(" | ")} |`,
  );
  return [head, rule, ...body].join("\n") + "\n";
}

async function main() {
  const [providers, crawl, facts, photos] = await Promise.all([
    load("providers.json"),
    load("crawl.json"),
    load("facts.json"),
    load("photos.json"),
  ]);
  if (!providers.length) throw new Error("data/enrichment/providers.json missing; run the pipeline first");

  const c = byProvider(crawl);
  const f = byProvider(facts);
  const ph = byProvider(photos);
  const rows = providers
    .map((p) => ({ p, c: c.get(p.provider), f: f.get(p.provider), ph: ph.get(p.provider) }))
    .sort((a, b) => Boolean(b.p.website) - Boolean(a.p.website) || b.p.siteCount - a.p.siteCount);

  const withSite = rows.filter((r) => r.p.website).length;
  const viaGemini = rows.filter((r) => r.f?.method === "gemini").length;
  const intro = [
    "# Scraped provider data",
    "",
    "Everything the pipeline extracted from provider websites, one row per provider.",
    `Generated by \`node scripts/export-table.mjs\` on ${new Date().toISOString().slice(0, 10)}.`,
    "The same table is in [`scraped-table.csv`](scraped-table.csv) for spreadsheets.",
    "",
    `${rows.length} providers · ${withSite} with a verified website · ${viaGemini} read by Gemini.`,
    "All values describe the provider's website as a whole, not an individual site.",
    "",
    "",
  ].join("\n");

  const csvPath = path.join(ROOT, "data", "scraped-table.csv");
  const mdPath = path.join(ROOT, "data", "scraped-table.md");
  await writeFile(csvPath, toCsv(rows));
  await writeFile(mdPath, intro + toMarkdown(rows));
  console.log(`${rows.length} rows x ${COLUMNS.length} columns -> ${path.relative(ROOT, csvPath)}, ${path.relative(ROOT, mdPath)}`);
}

main().catch((e) => {
  console.error(e.message);
  process.exit(1);
});
